### ISSUE TITLE
Should adding metalinter disable default checks flycheck runs?

### ISSUE THREAD

**Issue by ddgenome** [favadi/flycheck-gometalinter#14]
By default in Go mode, flycheck supports several checkers by default:

1.  go-gofmt
2.  go-golint
3.  go-vet
4.  go-build or go-test
5.  go-errcheck
6.  go-unconvert
7.  go-megacheck

see http://www.flycheck.org/en/latest/languages.html#go

Of these, gometalinter runs runs golint, go vet, errcheck, unconvert, and megacheck by default.

Should flycheck-gometalinter remove the duplicates from `flycheck-checkers` when it adds gometalinter? megacheck in particular is quite CPU intensive.

**Comment by ddgenome** [comment]
Adding something like this should do it:

```lisp
(setq flycheck-checkers (remove 'go-gofmt (remove 'go-golint (remove 'go-vet (remove 'go-errcheck (remove 'go-megacheck (remove 'go-unconvert flycheck-checkers)))))))
```

**Comment by favadi** [comment]
@ddgenome I added flycheck-gometalinter to the begining of `flycheck-checkers` (https://github.com/favadi/flycheck-gometalinter/blob/c90ea1aba80ddfdf603c9ba731be302400fd6ba2/flycheck-gometalinter.el#L119) and as we don't define `next-checkers`, those builtin checkers should be disabled already.

**Comment by favadi** [comment]
Closing as it works as expected.
