### ISSUE TITLE
cannot find vendor packages

### ISSUE THREAD

**Issue by slidemonk** [favadi/flycheck-gometalinter#3]
When I run `gometalinter .` directly there are no such errors. Also `go build` can compile the code just fine. However, when I have this flycheck mode enabled in emacs, I get following errors:

```
could not import google.golang.org/grpc (cannot find package "google.golang.org/grpc" in any of: (interfacer)

unused global variable could not import google.golang.org/grpc (cannot find package "google.golang.org/grpc" in any of: (varcheck)

could not import google.golang.org/grpc (cannot find package "google.golang.org/grpc" in any of: (unconvert)

unused struct field could not import google.golang.org/grpc (cannot find package "google.golang.org/grpc" in any of: (structcheck)

error return value not checked (could not import google.golang.org/grpc (cannot find package "google.golang.org/grpc" in any of:) (errcheck)

could not import google.golang.org/grpc (cannot find package "google.golang.org/grpc" in any of: (aligncheck)
```

I even tried running tools like `interfacer` (reported in above errors) directly and it doesn't give out any errors either. So, I'm surprised why this flycheck mode is showing messages as if tools like interfacer could not find packages in vendor dir?

**Comment by nitingupta910** [comment]
My $GOPATH/src was a symlink which was probably confusing emacs lisp side of scripting (since running various go tools directly from CLI always worked). I copied over the src folder to GOPATH and now it's all working. Thanks.
