### ISSUE TITLE
Launch two gometalinters, one fast, one thorough

### ISSUE THREAD

**Issue by dsvensson** [favadi/flycheck-gometalinter#7]
Launch two gometalinters, one with the `fast` option to get some data back asap, and one without the `fast` option, to get the rest of the errors when they decide to show up.

**Comment by favadi** [comment]
I'm not sure about this, do you have an example of a flycheck checker that does this?

**Comment by dsvensson** [comment]
Ah, so flycheck doesn't really background async anything, just runs all the checkers sequentially? Otherwise flycheck itself supports a number of go-checkers, and this package adds gometalinter, so if it does asyncify stuff, this package is one example of what I mean, just that it would register multiple checkers into flycheck.

**Comment by favadi** [comment]
>  just runs all the checkers sequentially?

Yes. I'm not sure about this, so I will just close it. If you still want it, please create a PR yourself.
